### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by wimvanderbauwhede** [mk270/blizanci#1]
Hi, I just now (17 Jan 2021) pulled the latest version and tried to build it with `rebar3 release`. It fails on the last step as follows:

===> Compiling apps/blizanci/src/blizanci_gemini.erl failed
apps/blizanci/src/blizanci_gemini.erl:51: undefined callback function start_link/3 (behaviour 'ranch_protocol')

I have Erlang/OTP 21 [erts-10.2.4] [source] [smp:4:4] [ds:4:4:10] [async-threads:1]

**Comment by wimvanderbauwhede** [comment]
It's OK, I found it. My build used ranch v2.0, there was an API change. I downgraded to ranch v1.7 and it build.

Cheers!

**Comment by mk270** [comment]
It sounds like we should pin the ranch version to 1.7, or amend the code?

**Comment by wimvanderbauwhede** [comment]
I just changed ranch to {ranch, "1.7.0"} in the config file. It then compiles fine. It does not work though, I get an"unknown POSIX error" on the first ranch API call. So maybe upgrading to v2.0 might be better. Thanks!

Wim

**Comment by mk270** [comment]
My running copy is on 1.7.1 - it does seem that it should be ported forward to 2.0

Did you get a traceback from this error? Thanks for reporting!

**Comment by mk270** [comment]
looks like 2.0 completely changes the API - you no longer get the underlying socket from the `start_link` callback; maybe there's a call to retrieve it.

**Comment by mk270** [comment]
Probably fixed in a17f55e24c4651
